name: Agoric SDK restore Node.js build
description: 'Set up Node.js environment and restore cached built files'

inputs:
  node-version:
    description: 'The version of Node.js to use'
    required: true
  xsnap-random-init:
    description: Build xsnap binary with random memory init
    required: false
    default: '0'

runs:
  using: composite
  steps:
    - name: set default environment variables
      run: echo ESM_DISABLE_CACHE=true >> $GITHUB_ENV
      shell: bash
    - uses: actions/checkout@v2
      with:
        clean: 'false'
        submodules: 'true'
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node-version }}
    - uses: kenchan0130/actions-system-info@master
      id: system-info
    - name: cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-${{ runner.arch }}-${{ steps.system-info.outputs.release }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-${{ steps.system-info.outputs.release }}-yarn-
    - name: restore built files
      id: built
      uses: actions/cache@v1
      with:
        path: .
        key: ${{ runner.os }}-${{ runner.arch }}-${{ steps.system-info.outputs.release }}-node-${{ inputs.node-version }}-built-${{ inputs.xsnap-random-init }}-${{ github.sha }}
    # This and the git diff below are to detect if `yarn install` results in a
    # change to the lock file.
    - name: yarn install
      run: yarn install
      shell: bash
      if: steps.built.outputs.cache-hit != 'true'
    - name: git diff --exit-code yarn.lock
      run: git diff --exit-code yarn.lock
      shell: bash
    - name: yarn build
      run: yarn build
      shell: bash
      if: steps.built.outputs.cache-hit != 'true'
      env:
        XSNAP_RANDOM_INIT: ${{ inputs.xsnap-random-init }}
